# Generated by Django 2.1.5 on 2024-01-25 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20240125_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='view',
            new_name='views',
        ),
    ]
